### ISSUE TITLE
Feature Request: initWithData:

### ISSUE THREAD

**Issue by peekpt** [DevFatani/Web_Vuw#4]
Currently it's possible to load html data like this: 

```
initFromUrl: Uri.dataFromString (yourHtmlStringGoesHere,
                     parameters: {"charset": "utf-8"},
                     mimeType: 'text/html')
                     .toString()
```

would it be possible to add something like

` initFromData: WebVuWData("<b>Hello Wold</b>", parameters: {"charset": "utf-8"},mimeType: 'text/html')`

of course the last two to be default and can be omitted

**Comment by DevFatani** [comment]
next update goal 👍🏻

**Comment by peekpt** [comment]
That's great! 
I'm having trouble inserting it in a Sliver. Because it needs to have an height to work, but if I define an Height I have scroll limited at that height. Is that someway that I can make the widget expand to when the page is all rendered?  That would be useful for api that output html, but we can't know it's size before rendering. Thank you!

**Comment by DevFatani** [comment]
sorry for late reply you can check new update

**Comment by peekpt** [comment]
I was informed that this method is limited by 2000 chars

Na(o) quarta, 30/01/2019, 19:23, Muhammad Fatani <notifications@github.com>
escreveu:
