### ISSUE TITLE
Unable to start on IOS device

### ISSUE THREAD

**Issue by Winner28** [DevFatani/Web_Vuw#7]
Xcode's output:
↳
    === BUILD TARGET firebase_auth OF PROJECT Pods
    WITH CONFIGURATION Debug ===
    /Users/bagdeyvgmail.com/.pub-cache/hosted/pub.dart
    lang.org/web_vuw-0.2.2/ios/Classes/WebVuwPlugin.m:
    2:9: fatal error: 'web_vuw/web_vuw-Swift.h' file
    not found
    #import "web_vuw/web_vuw-Swift.h"
            ^~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.

Flutter (Channel stable, v1.2.1, on Mac OS X 10.14.3 18D109)

**Comment by DevFatani** [comment]
did you install pod?
open terminal
go to your project and `ios` dir and then `pod install` and then `pod update`
